name: barfly.ai
github.url: https://owen9825.github.io/barfly.ai/
description: A stylish blog using the Solarized color palette
baseurl : /barlfly.ai

permalink: /:year/:month/:day/:title/
paginate: 10

plugins: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
